/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
  // Apply the java-library plugin for API and implementation separation.
  `java-library`
  id("com.github.johnrengelman.shadow") version "8.1.1"
  id("com.diffplug.spotless") version "6.22.0"
}

repositories {
  mavenCentral()
  maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/") /* Spigot API */
  maven("https://repo.mikeprimm.com/") /* Dynmap */
  maven("https://jitpack.io/") /* furplag/relic */
}

dependencies {
  compileOnly("org.spigotmc:spigot-api:1.20.2-R0.1-SNAPSHOT")
  compileOnly("us.dynmap:DynmapCoreAPI:3.6")

  compileOnly("org.projectlombok:lombok:1.18.30")
  annotationProcessor("org.projectlombok:lombok:1.18.30")
  implementation("com.github.furplag:relic:5.1.0")
}

spotless {
  java {
    endWithNewline()
    indentWithSpaces(2)
    removeUnusedImports()
    trimTrailingWhitespace()
  }
}

java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}

tasks {
  shadowJar {
    archiveBaseName.set("DynmapStructureMarkers")
    archiveAppendix.set("Spigot")
    archiveVersion.set("1.0.0-SNAPSHOT")
    archiveClassifier.set("")
    dependencies {
      include(dependency("com.github.furplag:relic:"))
    }
    relocate("jp.furplag.sandbox", "jp.furplag.sandbox.relic")
  }
}

tasks.named("jar") {
  finalizedBy("shadowJar")
}
