---
name: "$name"
version: "$version"
main: "jp.furplag.spigotmc.dynmap.extension.StructureMarkers"
description: "$description"
website: "https://github.com/furplag/dynmap-structure-markers/"
api-version: "$apiVersion"
api: "$apiVersion"
load: "POSTWORLD"
depend: [ dynmap ]
authors: [ furplag ]
