name: dynmap-structure-markers
description: auto generate structure markers into Dynmap .
load: POSTWORLD
version: 1.0.0-SNAPSHOT
api-version: '1.20'
main: jp.furplag.spigotmc.dynmap.extension.StructureMarkers
depend: [ dynmap ]
authors: [ furplag ]
